import React from 'react'
import { Link } from 'react-router-dom'
import styles from '../../../style'
import { informationBaseData, eCommerceData } from './ServicesContents'
const WebDevelopment = () => {
    return (
        <>
            <div className={`${styles.maxWidth} ${styles.paddingX} mx-auto text-white`}>
                <div className="bg-[#1cb04e]">
                    <img className="max-w-[80%] mx-auto" src={require('../../../assets/images/services/Web-development.svg').default} alt="Web-Devlopment" />
                </div>

                <div className="md:py-20 py-8">
                    <h1 className="text-3xl mb-8">Get Positive Results with our Best Web Design Services</h1>
                    <div className="text-justify gap-2 grid grid-cols-1">
                        <p>
                            We are like a spider – web development company as we craft the perfect web for your customers to stick on your website. It’s highly recommended — or rather virtually mandatory — to have an optimized responsive website. Any respectable company must have a quality corporate website as it will help in developing an application later on. Many will be inclined to visit your website, rather than driving a car to your physical location and browsing for your products. From a customer’s point of view, it’s better for them if they don’t have to ask anything and can just find what they’re looking for on your online site. An ideal website or web design is requisite to stand out from the rest in an appreciable way and our web development company is adept in that. Customers are searching for your website for contact information and comparing your website to competitors to determine who suits their needs the best. Unfortunately not every business owner sees the value in spending money to have a website professionally built, to reflect their business and personality. Our web development company lays special emphasis on websites to increase all the online traffic. One of the big terms in online marketing these days is “SEO”. SEO or Search Engine Optimization is the optimization of your website to provide a higher ranking among today’s search engines. When people are searching for a specific business or service to suit their needs, they are searching for key terms within these search engines. Statistically, these users will visit the first or second business that is generated by their search results. Your site is outdated, which means it does not contain the specific content necessary to be picked up and indexed by these search engines.
                        </p>
                        <p>
                            Aghori is a website development company based in Malad, we offer a diligent workforce that caters to your web development and designing goals, keeping your requirements intact. Our service offers benefits such as increased mobile traffic, quick development at a minimum price, lower maintenance needs, improved SEO, optimum online browsing experience, and prioritize extreme viewport sizes along with fast web page responses.
                        </p>
                    </div>

                    <img className="max-w-[80%] mx-auto py-16" src={require('../../../assets/images/services/Web-development-design-Responsive.svg').default} alt="Web-Devlopment" />

                </div>

                {/* Information Based start */}
                <hr />
                <div className="md:py-20 py-10 gap-4 grid grid-cols-1 md:grid-cols-6 text-justify">
                    {/* Heading*/}
                    <div className="col-span-2">
                        <h3 className="text-3xl md:text-5xl leading-normal mb-10"><span className="font-extralight ">Information</span><br /> Based</h3>
                        <p>
                            Approach the market with a website that looks like a replica of your business ethics. We develop informational websites incorporating our market insight and years of experience to make your presence felt.
                        </p>
                    </div>

                    {/* Images  */}
                    <div className="col-span-4 md:pl-10">
                        <div className="grid grid-cols-2 md:grid-cols-2 gap-2 mb-8">

                            {informationBaseData.map((infoBase) => (
                                <>
                                    {/* Icon-box */}
                                    <div>
                                        <a href={infoBase.imageLink} target_blank>
                                            <img src={infoBase.webImg} alt={infoBase.imageTitle} className="w-[75%] mx-auto" />
                                        </a>
                                    </div>
                                </>
                            ))}

                        </div>
                    </div>
                </div>
                {/* Information Based End */}

                {/* E-commerce start */}
                <hr />
                <div className="md:py-20 py-10 gap-4 grid grid-cols-1 md:grid-cols-6 text-justify">
                    {/* Heading*/}
                    <div className="col-span-2">
                        <h3 className="text-3xl md:text-5xl leading-normal mb-10"><span className="font-extralight ">E</span> - Commerce</h3>
                        <p>
                            Designing of an E-commerce website is the core to the success of the business. The more attractive you make it, the more business you make out of it. We make your E-commerce platform look like a professional store with easy to use interface engaging more customers and realized.
                        </p>
                    </div>

                    {/* Images  */}
                    <div className="col-span-4 md:pl-10">
                        <div className="grid grid-cols-2 md:grid-cols-2 gap-2 mb-8">

                            {eCommerceData.map((eCommerce) => (
                                <>
                                    {/* Icon-box */}
                                    <div>
                                        <a href={eCommerce.imageLink} target_blank>
                                            <img src={eCommerce.webImg} alt={eCommerce.imageTitle} className="w-[75%] mx-auto" />
                                        </a>
                                    </div>
                                </>
                            ))}

                        </div>
                    </div>
                </div>
                <hr />
                {/* Information Based End */}




                {/* Navigation start */}
                <div className="w-full flex justify-between py-8 md:py-12">
                    <Link to="#" className="text-sm md:text-2xl underline underline-offset-1">Previous Service</Link>
                    <Link to="#" className="text-sm md:text-2xl underline underline-offset-1">See all Services</Link>
                    <Link to="#" className="text-sm md:text-2xl underline underline-offset-1">Next Service</Link>
                </div>
                {/* Navigation start */}

            </div>

        </>
    )
}

export default WebDevelopment